# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# Use Node.js LTS as the base image
FROM node:20-slim AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies including devDependencies needed for build
# Smithery will optimize this by separating dev dependencies later if possible.
RUN --mount=type=cache,target=/root/.npm npm ci --ignore-scripts

# Copy source code
COPY . .

# Build the package
RUN --mount=type=cache,target=/root/.npm npm run build

# Minimal image for runtime
FROM node:20-slim

# Set working directory
WORKDIR /app

# Copy only necessary production files from builder
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/bin/ ./bin/
COPY --from=builder /app/scripts/ ./scripts/
COPY --from=builder /app/specs/ ./specs/
# If npm run build outputs to a different directory like 'dist' or 'build', ensure that's copied too.
# Assuming 'npm run build' compiles TypeScript to 'bin/' or similar as per tsconfig.json

# Install production dependencies
RUN --mount=type=cache,target=/root/.npm npm ci --omit=dev --ignore-scripts

# Set default environment variables (if any are universally needed)
# ENV OPENAPI_MCP_HEADERS="{}" # We removed reliance on this for base URL.

# Expose port if your app listens on one (Smithery might inject PORT)
# For stdio, this is not strictly for the app, but good practice for platform integration.
EXPOSE 8080

# Command to run the server
CMD ["npm", "start"]
